CREATE TABLE DEPARTMENT(DEPTCODE VARCHAR2(4) NOT NULL PRIMARY KEY,DEPTNAME VARCHAR2(15) NOT NULL,HOD VARCHAR2(4) NOT NULL,CHECK(DEPTCODE IN ('CSE','IT', 'CA', 'CHEM', 'MTHS', 'PHYS', 'HUM', 'BBA')));



CREATE TABLE FACULTY(FACULTYCODE VARCHAR2(4) NOT NULL PRIMARY KEY,
CHECK(FACULTYCODE LIKE 'F%'),
FACULTYNAME VARCHAR2(15) NOT NULL,
DATEOFJOIN DATE NOT NULL,
DEPTCODE VARCHAR2(4) NOT NULL,
CHECK (DEPTCODE IN ('CSE','IT','MCA','CA','CHEM','MTHS','PHYS','HUM','BBA')));

INSERT INTO DEPARTMENT VALUES('CSE','COMPUTER','AK');
INSERT INTO DEPARTMENT VALUES('PHYS','ELECTRONIC','IM');
INSERT INTO DEPARTMENT VALUES('IT','INFOTECH','SS');
INSERT INTO DEPARTMENT VALUES('BBA','COMPAPP','SC');
INSERT INTO DEPARTMENT VALUES('HUM','HUMANITIES','DC');
INSERT INTO DEPARTMENT VALUES('MTHS','MATHS','KKS');



INSERT INTO FACULTY VALUES('FHH','ANANYA MAM',TO_DATE('15-02-1985','DD-MM-YYYY'),'CSE');
INSERT INTO FACULTY VALUES('FAA','IVY MAM',TO_DATE('25-08-1985','DD-MM-YYYY'),'IT');
INSERT INTO FACULTY VALUES('FBB','PHULTULI MAM',TO_DATE('03-08-1999','DD-MM-YYYY'),'CSE');
INSERT INTO FACULTY VALUES('FCC','PAPRI MAM',TO_DATE('13-05-2015','DD-MM-YYYY'),'PHYS');
INSERT INTO FACULTY VALUES('FDD','KKS MAM',TO_DATE('15-02-2005','DD-MM-YYYY'),'MTHS');
INSERT INTO FACULTY VALUES('FEE','DCD MAM',TO_DATE('14-05-1998','DD-MM-YYYY'),'HUM');



alter table FACULTY  add  FOREIGN KEY (DEPTCODE) REFERENCES DEPARTMENT(DEPTCODE);
SELECT FACULTYNAME FROM FACULTY WHERE DEPTCODE =  'CSE';
SELECT COUNT(*) FROM FACULTY WHERE DEPTCODE= 'CA';
SELECT DEPTCODE ,HOD FROM DEPARTMENT;
alter table FACULTY add SALARY Number(8,2);
update FACULTY set SALARY= 50000.50;
SELECT FACULTYNAME FROM FACULTY WHERE SALARY >=8000;
SELECT FACULTYNAME FROM FACULTY WHERE DATEOFJOIN LIKE '%-08-%';

SELECT FACULTYNAME, DEPTNAME FROM DEPARTMENT D INNER JOIN FACULTY F ON D.DEPTCODE=F.DEPTCODE  WHERE F.SALARY BETWEEN 6000 AND 120000;

