SELECT NAME,ROLLNO FROM STUDENT WHERE YEAR='2';
SELECT NAME FROM STUDENT WHERE DEPTCODE!='CSE';
SELECT COUNT(REGNO) AS NOOFSTUDENTS,DEPTCODE FROM STUDENT GROUP BY DEPTCODE;
SELECT DEPTCODE,FACULTYNAME FROM FACULTY WHERE FACULTYCODE IN (SELECT HOD FROM DEPARTMENT);
SELECT COUNT(*) FROM FACULTY WHERE TO_CHAR(DATEOFJOIN,'MM')='01';
SELECT FACULTYNAME,SALARY FROM FACULTY WHERE (SALARY>=8000 AND SALARY<=20000);
SELECT FACULTYNAME FROM FACULTY WHERE FACULTYNAME LIKE 'S%' AND TO_CHAR(DATEOFJOIN,'YY')<'10';
ALTER TABLE FACULTY ADD SALARY NUMBER(8,2);

UPDATE FACULTY SET SALARY=8500 WHERE FACULTYCODE='FABC';
UPDATE FACULTY SET SALARY=7500 WHERE FACULTYCODE='FTRV';
UPDATE FACULTY SET SALARY=13500 WHERE FACULTYCODE='FMCH';
UPDATE FACULTY SET SALARY=8750 WHERE FACULTYCODE='FEMM';
UPDATE FACULTY SET SALARY=9000 WHERE FACULTYCODE='FRTN';
UPDATE FACULTY SET SALARY=2500 WHERE FACULTYCODE='FJHN';
UPDATE FACULTY SET SALARY=8500 WHERE FACULTYCODE='FADR';
UPDATE FACULTY SET SALARY=9000 WHERE FACULTYCODE='FSKL';

SELECT FACULTYNAME FROM FACULTY F1 WHERE SALARY>(SELECT AVG(SALARY) FROM FACULTY F WHERE F1.DEPTCODE=F.DEPTCODE);
SELECT DEPTCODE,COUNT(*) FROM STUDENT GROUP BY DEPTCODE ORDER BY DEPTCODE;
SELECT AVG(COUNT(*)) FROM STUDENT GROUP BY DEPTCODE;
