CREATE TABLE SUBJECT(
SUBJECTCODE VARCHAR2(4) NOT NULL PRIMARY KEY,
SUBJECTNAME VARCHAR2(15) NOT NULL,
FACULTYCODE VARCHAR2(4) NOT NULL,
FOREIGN KEY (FACULTYCODE) REFERENCES FACULTY (FACULTYCODE));


INSERT INTO SUBJECT VALUES('CS01', 'DBMS', 'FHH');
INSERT INTO SUBJECT VALUES('IT01', 'SOFTWARE', 'FAA');
INSERT INTO SUBJECT VALUES('CS02', 'OS', 'FBB');
INSERT INTO SUBJECT VALUES('PH01', 'LIGHT', 'FCC');
INSERT INTO SUBJECT VALUES('M01', 'ALGEBRA', 'FDD');
INSERT INTO SUBJECT VALUES('HU01', 'CHARECTER', 'FEE');

SELECT DEPTCODE,COUNT(*) FROM FACULTY GROUP BY DEPTCODE;

UPDATE FACULTY SET SALARY = SALARY + 500.00;


(SELECT NAME FROM STUDENT WHERE STUDENT.NAME LIKE 'S%') UNION (SELECT FACULTYNAME FROM FACULTY WHERE FACULTY.FACULTYNAME LIKE 'S%');


SELECT * FROM STUDENT WHERE ADDRESS = 'Kaikhali';

SELECT * FROM DEPARTMENT WHERE HOD IS NOT NULL;

SELECT FACULTYNAME FROM FACULTY WHERE DEPTCODE = 'IT';

SELECT * FROM FACULTY WHERE HOD IS NOT NULL;
